version: '3.8'

services:
  postgres:
    container_name: 'chaxis'
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: chaxis
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chaxis
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
