name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Teste conexão SSH
        run: ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-228-31-193.sa-east-1.compute.amazonaws.com "echo 'Conexão SSH bem-sucedida'"

      - name: Deploy to EC2
        run: |
          ssh ubuntu@ec2-18-228-31-193.sa-east-1.compute.amazonaws.com << 'EOF'
          cd /home/ubuntu/chaxis-api
          git pull origin master
          npm install
          npx prisma migrate deploy
          npm run prebuild
          npm run build
          EOF
