name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-18-228-31-193.sa-east-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@ec2-18-228-31-193.sa-east-1.compute.amazonaws.com << 'EOF'
          cd /chaxis-api
          git pull origin master
          npm install
          npx prisma migrate deploy
          npm run prebuild
          npm run build
          EOF
